### ISSUE TITLE
Request for addition of the Diedrichsen cerebellum atlas

### ISSUE THREAD

**Issue by mwvoss** [PennLINC/xcpEngine#451]
Could the developers add the Diedrichsen cerebellum atlas to the available atlases:  http://www.diedrichsenlab.org/imaging/propatlas.htm

If possible, would love to see your step-by-step for how to do this, which could help answer issue #450  too.

**Comment by a3sha2** [comment]
@mwvoss  pls see #450

**Comment by a3sha2** [comment]
@mwvoss thank you.
you can now pull for new docker image `pennbbl/xcpengine:latest `
